events {}

http {
    # Определяем, является ли отправитель нашим внутренним Nginx (сеть 172.20.0.0/16 в Docker). Можем добавить различные диапазоны Локальные и Внешние
    map $remote_addr $xff_clean {
        # ~^192\.168\.0\.  $proxy_add_x_forwarded_for; # Если из локальной сети диапазона 192.168.0.0/24, берём старый XFF и добавляем текущий IP
        ~^172\.20\.  $proxy_add_x_forwarded_for; # Если изнутри сети, берём старый XFF и добавляем текущий IP
        default      $remote_addr;               # Если извне, уничтожаем пользовательский XFF и пишем только реальный IP
    }

    server {
        # Nginx слушает порт 80 (HTTP) для входящих запросов
        listen 80;

        location / {
            # Проверяем, куда слать: если в заголовке Host указан конкретный апстрим, 
            # шлем туда (для тестов цепочки), иначе — на приложение.
            resolver 127.0.0.11 valid=5s;
            
            set $upstream "app";
            if ($http_x_next_upstream != "") {
                set $upstream $http_x_next_upstream;
            }

            proxy_pass http://$upstream:8080;
            
            # Передаем вычисленный безопасный заголовок
            proxy_set_header X-Forwarded-For $xff_clean;
            
            # Дополнительно передаем заголовок X-Next-Upstream дальше по цепочке, если он есть
            proxy_set_header X-Next-Upstream $http_x_next_upstream;
            proxy_set_header Host $host;
        }
    }
}
